---
- name: Install docker for ubuntu 22
  hosts: default
  become: true
  tasks:
    - name: Install ca-certificates, curl
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
      with_items:
        - ca-certificates
        - curl
    - name: Create directory /etc/apt/keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    - name: Download docker key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
    - name: Generate Docker repository entry
      changed_when: false
      ansible.builtin.shell: |
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "{{ ansible_distribution_release }}") stable"
      register: docker_repo_entry
    - name: Write Docker repository entry to file
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: '{{ docker_repo_entry.stdout }}'
        create: true
        mode: "0644"
      become: true
    - name: Install docker-ce, docker-ce-cli, docker-compose-plugin
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present
        update_cache: true
