---
- name: Install portainer
  hosts: default
  become: true
  tasks:
    - name: Create volume for portainer
      community.general.docker_volume:
        name: portainer_data
        state: present
    #
    - name: Install portainer
      # docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
      community.general.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        ports:
          - 8000:8000
          - 9443:9443
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
